spring:
  datasource:
    url: jdbc:mysql://39.105.93.184:3306/activiti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    database-schema-update: true
    db-history-used: true
project:
  manifest:
    file:
      path: classpath:/default-project.json