spring:
  datasource:
    url: jdbc:mysql://*********:3306/activiti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    database-schema-update: true
    db-history-used: true