server:
  port: 9000
elasticjob:
  tracing:
    type: RDB
  regCenter:
    serverLists: 111.***********:2181
    namespace: elasticjob-namespace
    max-retries: 5
  jobs:
    simpleJob:
      elasticJobClass: com.example.elasticjob.job.SpringBootSimpleJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      overwrite: true
    dataflowJob:
      elasticJobClass: com.example.elasticjob.job.SpringBootDataflowJob
      cron: 0/30 * * * * ?
      shardingTotalCount: 2
      shardingItemParameters: 0=A, 1=B
      overwrite: true
spring:
  datasource:
    url: jdbc:mysql://****************:3306/elasticjoob?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  dump:
    port: 9888

